version: '3'
services:
  db:
    image: postgres:13
    env_file:
      - .env
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '${POSTGRESQL_PASSWORD}'
      POSTGRES_DB: nestjs
  test-db:
    image: postgres:13
    env_file:
      - .env
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '${POSTGRESQL_PASSWORD}'
      POSTGRES_DB: nestjs
